// ─── Currency Definitions ──────────────────────────────────────────────────

export interface CurrencyOption {
  code:   string; // 'NGN', 'USD', 'GBP', etc.
  symbol: string; // '₦', '$', '£', etc.
  name:   string; // 'Nigerian Naira', 'US Dollar', etc.
  flag:   string; // emoji flag '🇳🇬', '🇺🇸', '🇬🇧'
}

export const CURRENCIES: CurrencyOption[] = [
  // ── Africa ──────────────────────────────────────────────────────────────
  { code: 'NGN', symbol: '₦',    name: 'Nigerian Naira',             flag: '🇳🇬' },
  { code: 'GHS', symbol: 'GH₵',  name: 'Ghanaian Cedi',              flag: '🇬🇭' },
  { code: 'KES', symbol: 'KSh',  name: 'Kenyan Shilling',            flag: '🇰🇪' },
  { code: 'ZAR', symbol: 'R',    name: 'South African Rand',          flag: '🇿🇦' },
  { code: 'EGP', symbol: 'E£',   name: 'Egyptian Pound',             flag: '🇪🇬' },
  { code: 'ETB', symbol: 'Br',   name: 'Ethiopian Birr',              flag: '🇪🇹' },
  { code: 'TZS', symbol: 'TSh',  name: 'Tanzanian Shilling',         flag: '🇹🇿' },
  { code: 'UGX', symbol: 'USh',  name: 'Ugandan Shilling',           flag: '🇺🇬' },
  { code: 'RWF', symbol: 'RF',   name: 'Rwandan Franc',              flag: '🇷🇼' },
  { code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham',            flag: '🇲🇦' },
  { code: 'TND', symbol: 'د.ت',  name: 'Tunisian Dinar',             flag: '🇹🇳' },
  { code: 'DZD', symbol: 'دج',   name: 'Algerian Dinar',             flag: '🇩🇿' },
  { code: 'LYD', symbol: 'LD',   name: 'Libyan Dinar',               flag: '🇱🇾' },
  { code: 'SDG', symbol: 'SDG',  name: 'Sudanese Pound',             flag: '🇸🇩' },
  { code: 'SOS', symbol: 'Sh',   name: 'Somali Shilling',            flag: '🇸🇴' },
  { code: 'XOF', symbol: 'CFA',  name: 'West African CFA Franc',     flag: '🌍' },
  { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc',  flag: '🌍' },
  { code: 'GNF', symbol: 'FG',   name: 'Guinean Franc',              flag: '🇬🇳' },
  { code: 'SLL', symbol: 'Le',   name: 'Sierra Leonean Leone',       flag: '🇸🇱' },
  { code: 'LRD', symbol: 'L$',   name: 'Liberian Dollar',            flag: '🇱🇷' },
  { code: 'MWK', symbol: 'MK',   name: 'Malawian Kwacha',            flag: '🇲🇼' },
  { code: 'ZMW', symbol: 'ZK',   name: 'Zambian Kwacha',             flag: '🇿🇲' },
  { code: 'ZWL', symbol: 'Z$',   name: 'Zimbabwean Dollar',          flag: '🇿🇼' },
  { code: 'BWP', symbol: 'P',    name: 'Botswana Pula',              flag: '🇧🇼' },
  { code: 'NAD', symbol: 'N$',   name: 'Namibian Dollar',            flag: '🇳🇦' },
  { code: 'MZN', symbol: 'MT',   name: 'Mozambican Metical',         flag: '🇲🇿' },
  { code: 'AOA', symbol: 'Kz',   name: 'Angolan Kwanza',             flag: '🇦🇴' },
  { code: 'MGA', symbol: 'Ar',   name: 'Malagasy Ariary',            flag: '🇲🇬' },
  { code: 'MUR', symbol: '₨',    name: 'Mauritian Rupee',            flag: '🇲🇺' },
  { code: 'SCR', symbol: '₨',    name: 'Seychellois Rupee',          flag: '🇸🇨' },
  { code: 'DJF', symbol: 'Fdj',  name: 'Djiboutian Franc',           flag: '🇩🇯' },
  { code: 'KMF', symbol: 'CF',   name: 'Comorian Franc',             flag: '🇰🇲' },
  { code: 'CVE', symbol: 'Esc',  name: 'Cape Verdean Escudo',        flag: '🇨🇻' },
  { code: 'STN', symbol: 'Db',   name: 'São Tomé Dobra',             flag: '🇸🇹' },
  { code: 'BIF', symbol: 'Fr',   name: 'Burundian Franc',            flag: '🇧🇮' },
  { code: 'CDF', symbol: 'FC',   name: 'Congolese Franc',            flag: '🇨🇩' },
  { code: 'GMD', symbol: 'D',    name: 'Gambian Dalasi',             flag: '🇬🇲' },
  { code: 'HTG', symbol: 'G',    name: 'Haitian Gourde',             flag: '🇭🇹' },
  { code: 'ERN', symbol: 'Nfk',  name: 'Eritrean Nakfa',             flag: '🇪🇷' },
  { code: 'LSL', symbol: 'L',    name: 'Lesotho Loti',               flag: '🇱🇸' },
  { code: 'SZL', symbol: 'L',    name: 'Swazi Lilangeni',            flag: '🇸🇿' },
  // ── Americas ────────────────────────────────────────────────────────────
  { code: 'USD', symbol: '$',    name: 'US Dollar',                  flag: '🇺🇸' },
  { code: 'CAD', symbol: 'C$',   name: 'Canadian Dollar',            flag: '🇨🇦' },
  { code: 'BRL', symbol: 'R$',   name: 'Brazilian Real',             flag: '🇧🇷' },
  { code: 'MXN', symbol: 'MX$',  name: 'Mexican Peso',               flag: '🇲🇽' },
  { code: 'ARS', symbol: '$',    name: 'Argentine Peso',             flag: '🇦🇷' },
  { code: 'CLP', symbol: '$',    name: 'Chilean Peso',               flag: '🇨🇱' },
  { code: 'COP', symbol: '$',    name: 'Colombian Peso',             flag: '🇨🇴' },
  { code: 'PEN', symbol: 'S/.',  name: 'Peruvian Sol',               flag: '🇵🇪' },
  { code: 'VES', symbol: 'Bs.S', name: 'Venezuelan Bolívar',         flag: '🇻🇪' },
  { code: 'UYU', symbol: '$U',   name: 'Uruguayan Peso',             flag: '🇺🇾' },
  { code: 'BOB', symbol: 'Bs.',  name: 'Bolivian Boliviano',         flag: '🇧🇴' },
  { code: 'PYG', symbol: '₲',    name: 'Paraguayan Guaraní',         flag: '🇵🇾' },
  { code: 'GTQ', symbol: 'Q',    name: 'Guatemalan Quetzal',         flag: '🇬🇹' },
  { code: 'HNL', symbol: 'L',    name: 'Honduran Lempira',           flag: '🇭🇳' },
  { code: 'NIO', symbol: 'C$',   name: 'Nicaraguan Córdoba',         flag: '🇳🇮' },
  { code: 'CRC', symbol: '₡',    name: 'Costa Rican Colón',          flag: '🇨🇷' },
  { code: 'PAB', symbol: 'B/.',  name: 'Panamanian Balboa',          flag: '🇵🇦' },
  { code: 'DOP', symbol: 'RD$',  name: 'Dominican Peso',             flag: '🇩🇴' },
  { code: 'JMD', symbol: 'J$',   name: 'Jamaican Dollar',            flag: '🇯🇲' },
  { code: 'TTD', symbol: 'TT$',  name: 'Trinidad & Tobago Dollar',   flag: '🇹🇹' },
  { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar',           flag: '🇧🇧' },
  { code: 'GYD', symbol: 'G$',   name: 'Guyanese Dollar',            flag: '🇬🇾' },
  { code: 'SRD', symbol: 'SRD',  name: 'Surinamese Dollar',          flag: '🇸🇷' },
  { code: 'BSD', symbol: 'B$',   name: 'Bahamian Dollar',            flag: '🇧🇸' },
  { code: 'BZD', symbol: 'BZ$',  name: 'Belize Dollar',              flag: '🇧🇿' },
  { code: 'XCD', symbol: 'EC$',  name: 'East Caribbean Dollar',      flag: '🌎' },
  { code: 'KYD', symbol: 'CI$',  name: 'Cayman Islands Dollar',      flag: '🇰🇾' },
  { code: 'BMD', symbol: '$',    name: 'Bermudian Dollar',           flag: '🇧🇲' },
  { code: 'AWG', symbol: 'ƒ',    name: 'Aruban Florin',              flag: '🇦🇼' },
  { code: 'ANG', symbol: 'ƒ',    name: 'Netherlands Antillean Guilder', flag: '🇨🇼' },
  { code: 'CUP', symbol: '$',    name: 'Cuban Peso',                 flag: '🇨🇺' },

  // ── Europe ──────────────────────────────────────────────────────────────
  { code: 'EUR', symbol: '€',    name: 'Euro',                       flag: '🇪🇺' },
  { code: 'GBP', symbol: '£',    name: 'British Pound',              flag: '🇬🇧' },
  { code: 'CHF', symbol: 'Fr',   name: 'Swiss Franc',                flag: '🇨🇭' },
  { code: 'NOK', symbol: 'kr',   name: 'Norwegian Krone',            flag: '🇳🇴' },
  { code: 'SEK', symbol: 'kr',   name: 'Swedish Krona',              flag: '🇸🇪' },
  { code: 'DKK', symbol: 'kr',   name: 'Danish Krone',               flag: '🇩🇰' },
  { code: 'PLN', symbol: 'zł',   name: 'Polish Złoty',               flag: '🇵🇱' },
  { code: 'CZK', symbol: 'Kč',   name: 'Czech Koruna',               flag: '🇨🇿' },
  { code: 'HUF', symbol: 'Ft',   name: 'Hungarian Forint',           flag: '🇭🇺' },
  { code: 'RON', symbol: 'lei',  name: 'Romanian Leu',               flag: '🇷🇴' },
  { code: 'BGN', symbol: 'лв',   name: 'Bulgarian Lev',              flag: '🇧🇬' },
  { code: 'HRK', symbol: 'kn',   name: 'Croatian Kuna',              flag: '🇭🇷' },
  { code: 'RSD', symbol: 'din.', name: 'Serbian Dinar',              flag: '🇷🇸' },
  { code: 'MKD', symbol: 'ден',  name: 'Macedonian Denar',           flag: '🇲🇰' },
  { code: 'ALL', symbol: 'L',    name: 'Albanian Lek',               flag: '🇦🇱' },
  { code: 'BAM', symbol: 'KM',   name: 'Bosnian Mark',               flag: '🇧🇦' },
  { code: 'ISK', symbol: 'kr',   name: 'Icelandic Króna',            flag: '🇮🇸' },
  { code: 'TRY', symbol: '₺',    name: 'Turkish Lira',               flag: '🇹🇷' },
  { code: 'UAH', symbol: '₴',    name: 'Ukrainian Hryvnia',          flag: '🇺🇦' },
  { code: 'RUB', symbol: '₽',    name: 'Russian Ruble',              flag: '🇷🇺' },
  { code: 'GEL', symbol: '₾',    name: 'Georgian Lari',              flag: '🇬🇪' },
  { code: 'AMD', symbol: '֏',    name: 'Armenian Dram',              flag: '🇦🇲' },
  { code: 'AZN', symbol: '₼',    name: 'Azerbaijani Manat',          flag: '🇦🇿' },
  { code: 'BYN', symbol: 'Br',   name: 'Belarusian Ruble',           flag: '🇧🇾' },
  { code: 'MDL', symbol: 'L',    name: 'Moldovan Leu',               flag: '🇲🇩' },
  { code: 'HKD', symbol: 'HK$',  name: 'Hong Kong Dollar',           flag: '🇭🇰' },

  // ── Middle East ─────────────────────────────────────────────────────────
  { code: 'AED', symbol: 'د.إ',  name: 'UAE Dirham',                 flag: '🇦🇪' },
  { code: 'SAR', symbol: '﷼',    name: 'Saudi Riyal',                flag: '🇸🇦' },
  { code: 'QAR', symbol: 'ر.ق',  name: 'Qatari Riyal',               flag: '🇶🇦' },
  { code: 'KWD', symbol: 'د.ك',  name: 'Kuwaiti Dinar',              flag: '🇰🇼' },
  { code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar',             flag: '🇧🇭' },
  { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial',                 flag: '🇴🇲' },
  { code: 'JOD', symbol: 'JD',   name: 'Jordanian Dinar',            flag: '🇯🇴' },
  { code: 'ILS', symbol: '₪',    name: 'Israeli New Shekel',         flag: '🇮🇱' },
  { code: 'LBP', symbol: 'ل.ل',  name: 'Lebanese Pound',             flag: '🇱🇧' },
  { code: 'IQD', symbol: 'ع.د',  name: 'Iraqi Dinar',                flag: '🇮🇶' },
  { code: 'IRR', symbol: '﷼',    name: 'Iranian Rial',               flag: '🇮🇷' },
  { code: 'YER', symbol: '﷼',    name: 'Yemeni Rial',                flag: '🇾🇪' },
  { code: 'SYP', symbol: 'LS',   name: 'Syrian Pound',               flag: '🇸🇾' },

  // ── Asia Pacific ────────────────────────────────────────────────────────
  { code: 'JPY', symbol: '¥',    name: 'Japanese Yen',               flag: '🇯🇵' },
  { code: 'CNY', symbol: '¥',    name: 'Chinese Yuan',               flag: '🇨🇳' },
  { code: 'INR', symbol: '₹',    name: 'Indian Rupee',               flag: '🇮🇳' },
  { code: 'KRW', symbol: '₩',    name: 'South Korean Won',           flag: '🇰🇷' },
  { code: 'SGD', symbol: 'S$',   name: 'Singapore Dollar',           flag: '🇸🇬' },
  { code: 'TWD', symbol: 'NT$',  name: 'New Taiwan Dollar',          flag: '🇹🇼' },
  { code: 'AUD', symbol: 'A$',   name: 'Australian Dollar',          flag: '🇦🇺' },
  { code: 'NZD', symbol: 'NZ$',  name: 'New Zealand Dollar',         flag: '🇳🇿' },
  { code: 'THB', symbol: '฿',    name: 'Thai Baht',                  flag: '🇹🇭' },
  { code: 'VND', symbol: '₫',    name: 'Vietnamese Đồng',            flag: '🇻🇳' },
  { code: 'IDR', symbol: 'Rp',   name: 'Indonesian Rupiah',          flag: '🇮🇩' },
  { code: 'MYR', symbol: 'RM',   name: 'Malaysian Ringgit',          flag: '🇲🇾' },
  { code: 'PHP', symbol: '₱',    name: 'Philippine Peso',            flag: '🇵🇭' },
  { code: 'PKR', symbol: '₨',    name: 'Pakistani Rupee',            flag: '🇵🇰' },
  { code: 'BDT', symbol: '৳',    name: 'Bangladeshi Taka',           flag: '🇧🇩' },
  { code: 'LKR', symbol: '₨',    name: 'Sri Lankan Rupee',           flag: '🇱🇰' },
  { code: 'NPR', symbol: '₨',    name: 'Nepalese Rupee',             flag: '🇳🇵' },
  { code: 'MMK', symbol: 'K',    name: 'Myanmar Kyat',               flag: '🇲🇲' },
  { code: 'KHR', symbol: '៛',    name: 'Cambodian Riel',             flag: '🇰🇭' },
  { code: 'LAK', symbol: '₭',    name: 'Lao Kip',                   flag: '🇱🇦' },
  { code: 'BND', symbol: 'B$',   name: 'Brunei Dollar',              flag: '🇧🇳' },
  { code: 'MOP', symbol: 'P',    name: 'Macanese Pataca',            flag: '🇲🇴' },
  { code: 'KZT', symbol: '₸',    name: 'Kazakhstani Tenge',          flag: '🇰🇿' },
  { code: 'UZS', symbol: 'лв',   name: 'Uzbekistani Som',            flag: '🇺🇿' },
  { code: 'AFN', symbol: '؋',    name: 'Afghan Afghani',             flag: '🇦🇫' },
  { code: 'FJD', symbol: 'FJ$',  name: 'Fijian Dollar',              flag: '🇫🇯' },
  { code: 'PGK', symbol: 'K',    name: 'Papua New Guinean Kina',     flag: '🇵🇬' },
  { code: 'SBD', symbol: 'SI$',  name: 'Solomon Islands Dollar',     flag: '🇸🇧' },
  { code: 'TOP', symbol: 'T$',   name: 'Tongan Paʻanga',             flag: '🇹🇴' },
  { code: 'WST', symbol: 'WS$',  name: 'Samoan Tālā',                flag: '🇼🇸' },
  { code: 'VUV', symbol: 'VT',   name: 'Vanuatu Vatu',               flag: '🇻🇺' },
  { code: 'KGS', symbol: 'лв',   name: 'Kyrgyzstani Som',            flag: '🇰🇬' },
  { code: 'TJS', symbol: 'SM',   name: 'Tajikistani Somoni',         flag: '🇹🇯' },
  { code: 'TMT', symbol: 'T',    name: 'Turkmenistani Manat',        flag: '🇹🇲' },
  { code: 'MVR', symbol: 'Rf',   name: 'Maldivian Rufiyaa',          flag: '🇲🇻' },
  { code: 'BTN', symbol: 'Nu',   name: 'Bhutanese Ngultrum',         flag: '🇧🇹' },
];

export const DEFAULT_CURRENCY: CurrencyOption = CURRENCIES[0]!;
